version: "2"
services:
  arm-build:
    build: .
    volumes:
      - "${TRAVIS_BUILD_DIR}:/source"
      - "./resin.key:/root/.ssh/id_rsa"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
      - TRAVIS_BRANCH=${TRAVIS_BRANCH}
      - TRAVIS_PULL_REQUEST_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH}
      - TARGET_REGISTRY_USERNAME=${TARGET_REGISTRY_USERNAME}
      - TARGET_REGISTRY_PASSWORD=${TARGET_REGISTRY_PASSWORD}
      - TARGET_IMAGE=${TARGET_IMAGE}
      - RESIN_REGISTRY_USERNAME=${RESIN_REGISTRY_USERNAME}
      - RESIN_API_KEY=${RESIN_API_KEY}
      - RESIN_REPO=${RESIN_REPO}
